export { createEmptyBoard, assignMinePower, placeMines, findWaterComponents, fillInaccessibleCells, createBoard } from './board'
export { adjacentMines, hasBoat, checkWinCondition, revealCell } from './cells'
export { findStartingPosition, initializeGame, cloneBoard, isInBounds, moveBoat, teleportBoat } from './navigation'
export { getBlastOffsets, explodeMines, handleMineStep } from './explosions'
export type { ExplosionResult } from './explosions'
export { nextFlagType, canFlag, isAdjacent, findRelocationTarget, flagCell } from './flagging'
